CUSTOMER_FEATURE_COLUMNS = [
    "tenure_months",
    "monthly_fee",
    "days_active_last_30",
    "support_tickets_last_30",
    "payment_delay_days",
    "nps_score",
    "plan",
]

CUSTOMER_NUMERIC_FEATURES = CUSTOMER_FEATURE_COLUMNS[:-1]
CUSTOMER_CATEGORICAL_FEATURES = ["plan"]
SENTIMENT_SCORE_COLUMN = "review_sentiment_score"
CHURN_NUMERIC_FEATURES = CUSTOMER_NUMERIC_FEATURES + [SENTIMENT_SCORE_COLUMN]
CHURN_FEATURE_COLUMNS = CUSTOMER_FEATURE_COLUMNS + [SENTIMENT_SCORE_COLUMN]
MONITORING_COLUMNS = CUSTOMER_FEATURE_COLUMNS + ["review_sentiment"]
